name: "Conftest"
description: "Write tests against structured configuration data using Open Policy Agent"
branding:
  icon: "check"
  color: "green"
inputs: 
  files:
    description: "Files for Conftest to test (space delimited)"
    required: true
  policy:
    description: "Where to find the policy folder or file"
    default: "policy"
  data:
    description: "Files or folder with supplemental test data"
  all-namespaces:
    description: "Whether to use all namespaces in testing"
    default: true
  combine:
    description: "Whether to combine input files"
  pull-url:
    description: "URL to pull policies from"
  pull-secret:
    description: "Secret that allows the policies to be pulled"
  add-comment:
    description: "Whether or not to add a comment to the PR"
    default: true
  docs-url:
    description: "The URL where users can find out more about the policies"
  gh-token:
    description: "The token that allows us to post a comment in the PR"
  gh-comment-url:
    description: "The URL of the comments for the PR"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    FILES: ${{ inputs.files }}
    POLICY: ${{ inputs.policy }}
    DATA: ${{ inputs.data }}
    ALL_NAMESPACES: ${{ inputs.all-namespaces }}
    COMBINE: ${{ inputs.combine }}
    PULL_URL: ${{ inputs.pull-url }}
    PULL_SECRET: ${{ inputs.pull-secret }}
    ADD_COMMENT: ${{ inputs.add-comment }}
    DOCS_URL: ${{ inputs.docs-url }}
    GITHUB_TOKEN: ${{ inputs.gh-token }}
    GITHUB_COMMENT_URL: ${{ inputs.gh-comment-url }}
